repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args:
          - --autofix
  - repo: git://github.com/igorshubovych/markdownlint-cli
    sha: v0.5.0
    hooks:
      - id: markdownlint
  - repo: git://github.com/pecigonzalo/pre-commit-shfmt
    sha: master
    hooks:
      - id: shell-fmt
        args:
          - --indent=4
  - repo: git://github.com/detailyang/pre-commit-shell
    sha: 1.0.2
    hooks:
    - id: shell-lint
