version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - run:
          name: Setup pre-commit
          command: sudo pip3 install pre-commit
      - checkout
      - restore_cache:
          keys:
            - dot-cache-pre-commit-{{ checksum ".pre-commit-config.yaml" }}
      - run:
          name: run tests
          command: make all
      - save_cache:
          key: dot-cache-pre-commit-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit
